jenkinsci/tekton-client-plugin

deploy.sh
Fixes https://github.com/jenkinsci/tekton-client-plugin/issues/7
- replace oc with kubectl for proper kubernetes support
=> Cheange deploy script to kubectl

.travis.yml, Makefile, src/main/kubernetes/deployment.yaml
Travis CI + KIND inital configuration.
=> TravisCI Initial Configuration

pom.xml, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/BaseStep.java, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateStep.java, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/delete/DeleteStep.java
- Change some of the functions from protected to private
- Add setter for tektonClient
=> Make CreateStep and DeleteTest more testable

pom.xml, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/TektonUtils.java, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/BaseStep.java, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateStep.java, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/delete/DeleteStep.java, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateStepTest.java, src/test/resources/taskrun-crd.yaml
- Refactor and add test for creation of TaskRun using Kubernetes Client MockServer
=> Add UnitTest for taskRunCreate

.travis.yml, Makefile, pom.xml, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateStep.java, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateStepTest.java, src/test/resources/task-crd.yaml
- Cobertura maven plugin support
- Codecov + travisci
- unit test for taskCreate
=> Add test for taskCreate and support for codecov.io

src/main/java/org/waveywaves/jenkins/plugins/tekton/client/TektonUtils.java, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateStep.java, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateStepMock.java, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateStepMockServerTest.java, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateStepTest.java
- improve stream handling
- create mock for CreateStep
- test runCreate using MockCreateStep
=> Unit Test and Refactoring for runCreate

.travis.yml, Makefile
fixes https://github.com/jenkinsci/tekton-client-plugin/issues/15
=> Install Tekton on KIND in TravisCI

docs/tutorial.md
Signed-off-by: vinamra28 <vinjain@redhat.com>
=> Fix cosmetic changes in tutorial

src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/delete/DeleteStep.java, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/delete/mock/DeleteStepMock.java, src/main/resources/org/waveywaves/jenkins/plugins/tekton/client/build/delete/DeleteStep/config.jelly, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/build/delete/DeleteStepMockServerTest.java, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/build/delete/DeleteStepTest.java
Add the DeleteAll functionality in DeleteStep which will delete all the resources of the selected Resource Type.
Closes #17 
Signed-off-by: vinamra28 <vinjain@redhat.com>
=> Add DeleteAll functionality in DeleteStep

src/main/java/org/waveywaves/jenkins/plugins/tekton/client/GlobalPluginConfiguration.java, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateStep.java, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/delete/DeleteStep.java, src/main/resources/org/waveywaves/jenkins/plugins/tekton/client/GlobalPluginConfiguration/config.jelly
=> Add Symbols for JCasc Support

src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateCustomTask.java, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/TektonWorkspaceDecl.java, src/main/resources/org/waveywaves/jenkins/plugins/tekton/client/build/create/TektonWorkspaceDecl/config.jelly
While defining workspaces in the task we can now mark it as whether it's
readOnly or not. Default is false
=> Add readOnly in Workspaces Declaration

pom.xml, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/ToolUtils.java
=> fix: minor spotbugs fix to allow build to succeed

Jenkinsfile
=> chore: add Jenkinsfile to build project on ci.jenkins.io

Jenkinsfile
=> chore: for now, only attempt to build the plugin on linux

pom.xml, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/BaseStep.java
BOM is updated to the oldest supported LTS version (at the point in time)
Added Spotbugs suppression
=> chore: update bom to 2.249.x

.github/workflows/cd.yaml
There are a number of other things that need to be configured for this to work, e.g.
https://github.com/jenkinsci/jep/blob/master/jep/229/README.adoc
=> chore: configure plugin for automatic release

.github/release-drafter.yml
=> chore: use the default release drafter config

README.md
=> chore: updated plugin badges to those in the plugin archetype

.github/release-drafter.yml, .mvn/extensions.xml, .mvn/maven.config, pom.xml
=> chore: add in config to generate 'changelist' for release

.mvn/maven.config
=> chore: enable the 'download-binaries' profile by default

src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateRaw.java
=> fix: make sure the workspace dir exists

.github/stale.yml
=> chore: configure stale-bot to close off older issues

.github/stale.yml
=> fix: update wontfix to stale for marking issues

.github/workflows/cd.yaml
=> fix: gha syntax

.github/workflows/cd.yaml
=> chore: only evaluate interesting categories on push

.github/workflows/cd.yaml
=> chore: enable release on interesting

.github/labeler.yml, .github/workflows/pr-labeler.yaml
=> chore: add a GHA to automatically add labels to PRs

pom.xml, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateRaw.java, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/mock/CreateRawMock.java, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/mock/FakeCreateRaw.java, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/logwatch/PipelineRunLogWatch.java, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/logwatch/TaskRunLogWatch.java, src/main/resources/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateRaw/config.jelly, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateRawMockServerTest.java, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateRawTest.java, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/build/delete/DeleteRawMockServerTest.java
so that you can use a custom namespace in the YAML or configure the namespace to use
fixes #96
=> fix: support optional namespace for pipelines

.github/workflows/pr-labeler.yaml
Switch to use the fork of the labeler until the outstanding PRs can be merged.
https://github.com/srvaroa/labeler/pull/24, https://github.com/srvaroa/labeler/pull/25 & https://github.com/srvaroa/labeler/pull/26
=> chore: switch to garethjevans/labeler for PRs labels

.github/workflows/cd.yaml
=> chore: add comment around jx-release-version

.github/labeler.yml
This check doesn't appear to be working correctly as it is adding "in progress" to everything.
=> chore: remove the mergeable: false check for wip PRs

src/main/java/org/waveywaves/jenkins/plugins/tekton/client/TektonUtils.java, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateRaw.java, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/logwatch/PipelineRunLogWatch.java, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/logwatch/TaskRunLogWatch.java
as there could be errors with the pipeline resource (missing
secret/volume/service account etc) so output the failure in the jenkins UI
to help users figure out why its not working
=> fix: add better error reporting if a pipeline does not start

pom.xml, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateRaw.java, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/logwatch/PipelineRunLogWatch.java, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/logwatch/TaskRunLogWatch.java, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateRawMockServerTest.java, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateRawTest.java, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/build/delete/DeleteRawMockServerTest.java
so that the job actually fails if the Pipeline/Task fails and if there is an exception log it to the users console
=> fix: report failed pipelines to run status

.github/workflows/cd.yaml
=> build(deps): bump setup-java action to v2

.github/workflows/cd.yaml
=> chore(deps): bump jx-release-version to 2.3.5

pom.xml
=> chore(deps): bump tekton-client to 5.3.1

pom.xml, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/TektonUtils.java, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateRaw.java, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/logwatch/PipelineRunLogWatch.java, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateRawMockServerTest.java, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/mock/CreateRawMock.java, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/mock/FakeCreateRaw.java, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/build/delete/DeleteRawMockServerTest.java
Currently setting `BUILD_ID`, `PULL_BASE_SHA` and `REPO_URL`
This is currently enough to use the `git-clone` task on the main/master branch
=> feat: add some default parameters when starting a pipelinerun

src/main/java/org/waveywaves/jenkins/plugins/tekton/client/logwatch/PipelineRunLogWatch.java, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/logwatch/TaskRunLogWatch.java
Prefix log messages from the tekton client with `[Tekton] ` to make it more obvious what are container logs
=> chore: improve logging output in console

src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateRaw.java
=> fix: use empty string as a default value for params

README.md, pom.xml
Now that we have basic pipeline support, it may make sense to advertise this as beta
=> chore: bump to beta

docs/tutorial.md
=> docs: added some basic pipeline usage docs

pom.xml, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateRaw.java
=> chore: improve logging when PipelineRun is started

docs/installation.md
=> docs: create a simple installation guide

README.md
=> docs: add a link to the installation guide

docs/tutorial.md
This step is required to ensure that the GIT_* variables are set.
=> docs: add the `checkout scm` step into the pipeline example

src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateRaw.java, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateRawTest.java
=> chore: set extra parameters during build

src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateRaw.java
the previous logic was using a unqiue title that would add a new check
each time the PR ran
=> fix: correct the check title so duplicate checks are not received

src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateRaw.java, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateRawTest.java
=> feat: record a successful check at the end of a pipeline

.mvn/maven.config, pom.xml
=> feat: switch to RC for prerelease

src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateRaw.java, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/build/FakeChecksPublisher.java, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateRawMockServerTest.java, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateRawTest.java
=> fix: added tests around github checks

docs/tutorial.md
=> docs: updated installation docs with parameters passed to pipelines

src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateRaw.java, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateRawMockServerTest.java, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/JenkinsTest.java, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/build/delete/DeleteRawMockServerTest.java
=> fix: record failure if pipelinerun fails to start

src/test/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateRawTest.java, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/build/delete/DeleteRawTest.java
=> chore: switch to hamcreast asserts/matchers

.github/workflows/e2e.yml, pom.xml, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/CreateRaw.java, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/logwatch/TaskRunLogWatch.java, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/JenkinsFreestyleTest.java, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/JenkinsPipelineTest.java
=> fix: corrected running in a different namespace

.github/workflows/cd.yaml
=> fix: correct cd pipeline

README.md
=> chore: add a simple demo to the main page

src/test/java/org/waveywaves/jenkins/plugins/tekton/client/build/create/JenkinsPipelineTest.java
Ensure the pipeline reports the correct error when multiple docs are used.
=> chore: add a pipeline test for multiple documents

roadmap.md
=> docs: updated the roadmap post v1.0.0

docs/tutorial.md
Remove PipelineResource from tutorial, because create and delete PipelineResource is not supported.
=> docs: remove PipelineResource from tutorial

.github/workflows/e2e.disabled, pom.xml
=> fix: latest java8 build fix

.github/workflows/javadoc.yml, .github/workflows/spotbugs.yml
=> chore: add in javadoc and spotbugs checks as these can break the release

README.md
Plugin site auditing is warning about http images on https site.
=> Update http links to https:

README.md
I added a Community section to the README for better clarity. It includes a link to the Gitter channel.
=> Add Community Section

.github/workflows/cd.yaml, .github/workflows/e2e.disabled, .github/workflows/javadoc.yml, .github/workflows/spotbugs.yml, Jenkinsfile, pom.xml, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/global/TektonGlobalConfiguration.java
Reverts jenkinsci/tekton-client-plugin#363
=> Revert "feat(java): Require Jenkins core 2.479.3 and Java 17"

.github/dependabot.yml
Update dependabot `maven` packages update intervals from "weekly" to "daily"
N/A
=> chore: update maven package schedule interval to daily in dependabot.yml

pom.xml
Updated the `revision` version to match the one on GitHub
N/A
=> chore: update revision version in pom.xml

pom.xml, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/build/delete/DeleteRaw.java
1. Cleaned up "pom.xml".
2. Updated `tekton-client` and `kubernetes-server-mock` to highest possible version. 
Not needed for the nature of this PR.
=> chore: update and clean up pom.xml

Jenkinsfile
=> Remove Windows support for CI

Makefile, pom.xml, scripts/e2e-test.sh, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/TektonUtils.java, src/main/java/org/waveywaves/jenkins/plugins/tekton/client/logwatch/TaskRunLogWatch.java, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/e2e/E2ETestBase.java, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/e2e/TektonCreatePipelineRunE2ETest.java, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/e2e/TektonCreateTaskRunE2ETest.java, src/test/java/org/waveywaves/jenkins/plugins/tekton/client/e2e/TektonDeleteE2ETest.java
This change adds a initial set of e2e tests
=> test: add initial e2e tests

Jenkinsfile
Testing is done on this PR as well to see what was failing in the Jenkins CI and solving any issues if necessary, in this case I saw that the e2e tests were being run by Jenkins which is not necessary so have removed them here
=> chore: do not test E2E using Jenkins CI
